version: '3.6'
services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: TRUDemo
    restart: always
    ports: 
      - 51773
      - 52782:52773
      - 53773
    volumes:
      - ./:/irisdev/app